In [28]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import root_mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv(r"D:\Datasets\Insure_auto.csv")
df

Branch  Home  Automobile  Operating_Cost
0    B01   400        1200          124000
1    B02   350         360           71000
2    B03   600         800          136000
3    B04   800        1800          219000
4    B05   900        1600          230000
5    B06   200        1000           75000
6    B07   120         900           56000
7    B08   340        1100          110000
8    B09   490         900          120000
9    B10   700         800          144000

In [5]:
x=df[['Home',"Automobile"]]
y=df['Operating_Cost']
x.shape,y.shape

((10, 2), (10,))

In [6]:
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [7]:
model.intercept_,model.coef_[0]

(np.float64(-10084.213130948774), np.float64(167.32668857228617))

In [8]:
x=df['Home']
x=x.to_numpy().reshape(-1,1)
x.shape

(10, 1)

## Transformation

In [9]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
x_poly=poly.fit_transform(x)


In [10]:
x_poly

x0      x0^2
0  400.0  160000.0
1  350.0  122500.0
2  600.0  360000.0
3  800.0  640000.0
4  900.0  810000.0
5  200.0   40000.0
6  120.0   14400.0
7  340.0  115600.0
8  490.0  240100.0
9  700.0  490000.0

In [11]:
model.fit(x_poly,y)
model.intercept_,model.coef_

(np.float64(54381.71562081708), array([57.28485112,  0.15387525]))

In [12]:
y_pred=model.intercept_+(model.coef_[0]*x)+(model.coef_[1]*x**2)
y_pred

array([[101915.6960768 ],
       [ 93281.13164386],
       [144147.7163113 ],
       [198689.75655014],
       [230577.03417119],
       [ 71993.69584664],
       [ 63471.70135579],
       [ 91646.5439073 ],
       [119396.74020679],
       [169879.98393018]])

In [13]:
root_mean_squared_error(y,y_pred)

15922.438797444005

In [14]:
r2_score(y,y_pred)

0.9172801092195866

In [15]:
y_model_pred=model.predict(x_poly)
y_model_pred

array([101915.6960768 ,  93281.13164386, 144147.7163113 , 198689.75655014,
       230577.03417119,  71993.69584664,  63471.70135579,  91646.5439073 ,
       119396.74020679, 169879.98393018])

In [16]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:-1],df['Operating_Cost'],test_size=0.3,random_state=40)

In [17]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7, 2), (3, 2), (7,), (3,))

In [18]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [19]:
y_pred=model.predict(X_test)

In [20]:
y_pred

array([225537.79059964, 219750.64144355, 120336.75264145])

In [21]:
r2_score(y_test,y_pred)

0.9971953259035071

Boston Housing

In [23]:
boston=pd.read_csv(r"D:\Datasets\Boston.csv")
x = boston.drop('medv',axis =1)
y = boston['medv']

In [30]:
lr  = LinearRegression()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 25)
lr.fit(x,y)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test,y_pred)

3.013565753239206

In [29]:
poly = PolynomialFeatures(degree = 2).set_output(transform='pandas')
x_poly = poly.fit_transform(x)
x_train,x_test,y_train,y_test = train_test_split(x_poly,y,test_size = 0.3,random_state = 25)
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test,y_pred)

2.6635485508633145

In [31]:
poly = PolynomialFeatures(degree = 3).set_output(transform='pandas')
x_poly = poly.fit_transform(x)
x_train,x_test,y_train,y_test = train_test_split(x_poly,y,test_size = 0.3,random_state = 25)
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test,y_pred)

193.45222162369058

Housing

In [46]:
housing = pd.read_csv(r"D:\Datasets\Housing.csv")

In [47]:
dum_hous = pd.get_dummies(housing,drop_first = True)
dum_hous

price  lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  \
0     42000.0     5850         3        1        2         1          True   
1     38500.0     4000         2        1        1         0          True   
2     49500.0     3060         3        1        1         0          True   
3     60500.0     6650         3        1        2         0          True   
4     61000.0     6360         2        1        1         0          True   
..        ...      ...       ...      ...      ...       ...           ...   
541   91500.0     4800         3        2        4         0          True   
542   94000.0     6000         3        2        4         0          True   
543  103000.0     6000         3        2        4         1          True   
544  105000.0     6000         3        2        2         1          True   
545  105000.0     6000         3        1        2         1          True   

     recroom_yes  fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
0          False          True      False      False         False  
1          False         False      False      False         False  
2          False         False      False      False         False  
3           True         False      False      False         False  
4          False         False      False      False         False  
..           ...           ...        ...        ...           ...  
541         True         False      False       True         False  
542        False         False      False       True         False  
543         True         False      False       True         False  
544         True         False      False       True         False  
545        False         False      False       True         False  

[546 rows x 12 columns]

In [51]:
x = dum_hous.drop('price', axis=1)
y = dum_hous['price']

In [52]:
lr = LinearRegression()
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25)
lr.fit(x, y)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test, y_pred)

11531.541198895688

In [53]:
poly = PolynomialFeatures(degree=2).set_output(transform='pandas')
x_poly = poly.fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x_poly, y, test_size=0.3, random_state=25)
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test, y_pred)

12967.811687249932

In [54]:
poly = PolynomialFeatures(degree=3).set_output(transform='pandas')
x_poly = poly.fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x_poly, y, test_size=0.3, random_state=25)
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test, y_pred)

18604.846319221444