In [83]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import root_mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

In [45]:
df=pd.read_csv(r"D:\Datasets\Insure_auto.csv")
df

Branch  Home  Automobile  Operating_Cost
0    B01   400        1200          124000
1    B02   350         360           71000
2    B03   600         800          136000
3    B04   800        1800          219000
4    B05   900        1600          230000
5    B06   200        1000           75000
6    B07   120         900           56000
7    B08   340        1100          110000
8    B09   490         900          120000
9    B10   700         800          144000

In [46]:
x=df[['Home',"Automobile"]]
y=df['Operating_Cost']
x.shape,y.shape

((10, 2), (10,))

In [47]:
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [48]:
model.intercept_,model.coef_[0]

(np.float64(-10084.213130948774), np.float64(167.32668857228617))

In [60]:
x=df['Home']
x=x.to_numpy().reshape(-1,1)
x.shape

(10, 1)

## Transformation

In [61]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
x_poly=poly.fit_transform(x)


In [81]:
x_poly

x0      x0^2
0  400.0  160000.0
1  350.0  122500.0
2  600.0  360000.0
3  800.0  640000.0
4  900.0  810000.0
5  200.0   40000.0
6  120.0   14400.0
7  340.0  115600.0
8  490.0  240100.0
9  700.0  490000.0

In [62]:
model.fit(x_poly,y)
model.intercept_,model.coef_

(np.float64(54381.71562081708), array([57.28485112,  0.15387525]))

In [63]:
y_pred=model.intercept_+(model.coef_[0]*x)+(model.coef_[1]*x**2)
y_pred

array([[101915.6960768 ],
       [ 93281.13164386],
       [144147.7163113 ],
       [198689.75655014],
       [230577.03417119],
       [ 71993.69584664],
       [ 63471.70135579],
       [ 91646.5439073 ],
       [119396.74020679],
       [169879.98393018]])

In [64]:
root_mean_squared_error(y,y_pred)

15922.438797444005

In [65]:
r2_score(y,y_pred)

0.9172801092195866

In [80]:
y_model_pred=model.predict(x_poly)
y_model_pred

array([101915.6960768 ,  93281.13164386, 144147.7163113 , 198689.75655014,
       230577.03417119,  71993.69584664,  63471.70135579,  91646.5439073 ,
       119396.74020679, 169879.98393018])

In [98]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:-1],df['Operating_Cost'],test_size=0.3,random_state=40)

In [99]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7, 2), (3, 2), (7,), (3,))

In [100]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [101]:
y_pred=model.predict(X_test)

In [107]:
y_pred

array([225537.79059964, 219750.64144355, 120336.75264145])

In [108]:
r2_score(y_test,y_pred)

0.9971953259035071

In [117]:
df=pd.read_csv(r"D:\Cases\Concrete_Strength\Concrete_Data.csv")
df

Cement  Blast    Fly  Water  Superplasticizer  Coarse   Fine  Age  \
0      540.0    0.0    0.0  162.0               2.5  1040.0  676.0   28   
1      540.0    0.0    0.0  162.0               2.5  1055.0  676.0   28   
2      332.5  142.5    0.0  228.0               0.0   932.0  594.0  270   
3      332.5  142.5    0.0  228.0               0.0   932.0  594.0  365   
4      198.6  132.4    0.0  192.0               0.0   978.4  825.5  360   
...      ...    ...    ...    ...               ...     ...    ...  ...   
1025   276.4  116.0   90.3  179.6               8.9   870.1  768.3   28   
1026   322.2    0.0  115.6  196.0              10.4   817.9  813.4   28   
1027   148.5  139.4  108.6  192.7               6.1   892.4  780.0   28   
1028   159.1  186.7    0.0  175.6              11.3   989.6  788.9   28   
1029   260.9  100.5   78.3  200.6               8.6   864.5  761.5   28   

      Strength  
0        79.99  
1        61.89  
2        40.27  
3        41.05  
4        44.30  
...        ...  
1025     44.28  
1026     31.18  
1027     23.70  
1028     32.77  
1029     32.40  

[1030 rows x 9 columns]

In [118]:
x=df.drop('Strength',axis=1)
y=df['Strength']

In [143]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.30)

## Simple linear regression

In [144]:
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

print("R2 score:",r2_score(y_test,y_pred))
print("Root Mean Squared:",root_mean_squared_error(y_test,y_pred))

R2 score: 0.5925312745577276
Root Mean Squared: 10.794889126878578


##  Polynomial features transformation

In [145]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
x_poly=poly.fit_transform(X_train)
x_poly.head(5)

Cement  Blast    Fly  Water  Superplasticizer  Coarse   Fine   Age  \
542   255.0    0.0    0.0  192.0               0.0   889.8  945.0  90.0   
37    332.5  142.5    0.0  228.0               0.0   932.0  594.0  90.0   
826   480.0    0.0    0.0  192.0               0.0   936.0  721.0   3.0   
530   359.0   19.0  141.0  154.0              10.9   942.0  801.0  56.0   
784   331.0    0.0    0.0  192.0               0.0   879.0  825.0   3.0   

      Cement^2  Cement Blast  ...  Superplasticizer^2  \
542   65025.00          0.00  ...                0.00   
37   110556.25      47381.25  ...                0.00   
826  230400.00          0.00  ...                0.00   
530  128881.00       6821.00  ...              118.81   
784  109561.00          0.00  ...                0.00   

     Superplasticizer Coarse  Superplasticizer Fine  Superplasticizer Age  \
542                      0.0                    0.0                   0.0   
37                       0.0                    0.0                   0.0   
826                      0.0                    0.0                   0.0   
530                  10267.8                 8730.9                 610.4   
784                      0.0                    0.0                   0.0   

      Coarse^2  Coarse Fine  Coarse Age    Fine^2  Fine Age   Age^2  
542  791744.04     840861.0     80082.0  893025.0   85050.0  8100.0  
37   868624.00     553608.0     83880.0  352836.0   53460.0  8100.0  
826  876096.00     674856.0      2808.0  519841.0    2163.0     9.0  
530  887364.00     754542.0     52752.0  641601.0   44856.0  3136.0  
784  772641.00     725175.0      2637.0  680625.0    2475.0     9.0  

[5 rows x 44 columns]

In [146]:
model.fit(x_poly,y_train)
y_pred=model.predict(poly.fit_transform(X_test))
print("R2 score:",r2_score(y_test,y_pred))
print("Root Mean Squared:",root_mean_squared_error(y_test,y_pred))

R2 score: 0.7959267276257528
Root Mean Squared: 7.63948548321734


with degree 3

In [147]:
poly=PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
x_poly=poly.fit_transform(X_train)
model.fit(x_poly,y_train)
y_pred=model.predict(poly.fit_transform(X_test))
print("R2 score:",r2_score(y_test,y_pred))
print("Root Mean Squared:",root_mean_squared_error(y_test,y_pred))

R2 score: 0.8676921916757397
Root Mean Squared: 6.1512557413415845


with degree 4 m

In [148]:
poly = PolynomialFeatures(degree=4, include_bias=False).set_output(transform='pandas')
x_poly = poly.fit_transform(X_train)
model.fit(x_poly, y_train)
y_pred = model.predict(poly.fit_transform(X_test))
print("R2 score:", r2_score(y_test, y_pred))
print("Root Mean Squared:", root_mean_squared_error(y_test, y_pred))

R2 score: -12.00944930878722
Root Mean Squared: 60.99588013403106


with degree 4

In [151]:
poly = PolynomialFeatures(degree=4, include_bias=False).set_output(transform='pandas')
x_poly = poly.fit_transform(X_train)
model.fit(x_poly, y_train)
y_pred = model.predict(poly.fit_transform(X_test))
print("R2 score:", r2_score(y_test, y_pred))
print("Root Mean Squared:", root_mean_squared_error(y_test, y_pred))

R2 score: -12.00944930878722
Root Mean Squared: 60.99588013403106
