In [19]:
import numpy as np
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

In [2]:
boston = pd.read_csv("C:/Python/Datasets/Boston.csv")
X = boston.drop('medv', axis=1)
y = boston['medv']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [13]:
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'error'])
df_scores.sort_values('error')

alpha     error
4    1.000  3.071007
3    0.500  3.072121
5    1.500  3.073661
6    2.000  3.077510
7    2.000  3.077510
2    0.100  3.100479
8    5.000  3.102838
9    5.000  3.102838
1    0.010  3.115621
0    0.001  3.117373
10  10.000  3.124733

In [17]:
ridge = Ridge(alpha=1)
ridge.fit(X, y)
ridge.coef_

array([-1.04595278e-01,  4.74432243e-02, -8.80467889e-03,  2.55239322e+00,
       -1.07770146e+01,  3.85400020e+00, -5.41453810e-03, -1.37265353e+00,
        2.90141589e-01, -1.29116463e-02, -8.76074394e-01,  9.67327945e-03,
       -5.33343225e-01])

In [20]:
lr = LinearRegression()
lr.fit(X, y)
lr.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [14]:
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
scores = []
for a in alphas:
    lasso = Lasso(alpha=a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'error'])
df_scores.sort_values('error')

alpha     error
1    0.010  3.088221
0    0.001  3.114200
2    0.100  3.129219
3    0.500  3.197794
4    1.000  3.373066
5    1.500  3.542921
6    2.000  3.573108
7    2.000  3.573108
8    5.000  3.856294
9    5.000  3.856294
10  10.000  3.942140

In [22]:
lasso = Lasso(alpha=0.01)
lasso.fit(X, y)
lasso.coef_

array([-1.06228354e-01,  4.68603033e-02,  6.47427472e-03,  2.50419017e+00,
       -1.43944776e+01,  3.81418583e+00, -1.81830336e-03, -1.42215548e+00,
        2.98525812e-01, -1.26273172e-02, -9.16368723e-01,  9.48546597e-03,
       -5.30481493e-01])

In [24]:
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
ratios = [0.001, 0.25, 0.5, 0.75, 1]
scores = []
for a in alphas:
    for r in ratios:
        elastic = ElasticNet(alpha=a, l1_ratio=r)
        elastic.fit(X_train, y_train)
        y_pred = elastic.predict(X_test)
        scores.append([a,r, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1_ratio', 'error'])
df_scores.sort_values('error')

alpha  l1_ratio     error
8    0.010     0.750  3.071908
0    0.001     0.001  3.077351
7    0.010     0.500  3.079164
1    0.001     0.250  3.082304
6    0.010     0.250  3.085807
9    0.010     1.000  3.088221
2    0.001     0.500  3.089473
5    0.010     0.001  3.092238
3    0.001     0.750  3.100139
4    0.001     1.000  3.114200
14   0.100     1.000  3.129219
13   0.100     0.750  3.149922
12   0.100     0.500  3.167589
11   0.100     0.250  3.179851
10   0.100     0.001  3.186468
19   0.500     1.000  3.197794
18   0.500     0.750  3.266077
17   0.500     0.500  3.306450
16   0.500     0.250  3.333951
15   0.500     0.001  3.349475
24   1.000     1.000  3.373066
23   1.000     0.750  3.395276
22   1.000     0.500  3.408006
21   1.000     0.250  3.417197
20   1.000     0.001  3.422455
25   1.500     0.001  3.455121
26   1.500     0.250  3.458059
27   1.500     0.500  3.466362
30   2.000     0.001  3.475825
35   2.000     0.001  3.475825
31   2.000     0.250  3.485971
36   2.000     0.250  3.485971
28   1.500     0.750  3.487664
32   2.000     0.500  3.509399
37   2.000     0.500  3.509399
29   1.500     1.000  3.542921
40   5.000     0.001  3.545296
45   5.000     0.001  3.545296
33   2.000     0.750  3.558736
38   2.000     0.750  3.558736
34   2.000     1.000  3.573108
39   2.000     1.000  3.573108
46   5.000     0.250  3.600538
41   5.000     0.250  3.600538
50  10.000     0.001  3.609039
42   5.000     0.500  3.675859
47   5.000     0.500  3.675859
51  10.000     0.250  3.753099
48   5.000     0.750  3.785710
43   5.000     0.750  3.785710
44   5.000     1.000  3.856294
49   5.000     1.000  3.856294
52  10.000     0.500  3.899711
53  10.000     0.750  3.912542
54  10.000     1.000  3.942140

#### Concrete Strength

In [27]:
concrete = pd.read_csv("C:/Python/Cases/Concrete_Strength/Concrete_Data.csv")
X = concrete.drop('Strength', axis=1)
y = concrete['Strength']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [29]:
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'error'])
df_scores.sort_values('error')

alpha     error
0    0.001  7.708183
1    0.010  7.708183
2    0.100  7.708183
3    0.500  7.708184
4    1.000  7.708184
5    1.500  7.708185
6    2.000  7.708186
7    2.000  7.708186
8    5.000  7.708192
9    5.000  7.708192
10  10.000  7.708200

In [30]:
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
scores = []
for a in alphas:
    lasso = Lasso(alpha=a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'error'])
df_scores.sort_values('error')

alpha     error
0    0.001  7.708198
1    0.010  7.708334
2    0.100  7.709691
3    0.500  7.715714
4    1.000  7.723271
5    1.500  7.731425
6    2.000  7.740793
7    2.000  7.740793
8    5.000  7.778317
9    5.000  7.778317
10  10.000  7.798394

In [31]:
alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
ratios = [0.001, 0.25, 0.5, 0.75, 1]
scores = []
for a in alphas:
    for r in ratios:
        elastic = ElasticNet(alpha=a, l1_ratio=r)
        elastic.fit(X_train, y_train)
        y_pred = elastic.predict(X_test)
        scores.append([a,r, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1_ratio', 'error'])
df_scores.sort_values('error')

alpha  l1_ratio     error
0    0.001     0.001  7.708184
1    0.001     0.250  7.708187
2    0.001     0.500  7.708191
3    0.001     0.750  7.708194
5    0.010     0.001  7.708196
4    0.001     1.000  7.708198
6    0.010     0.250  7.708230
7    0.010     0.500  7.708264
8    0.010     0.750  7.708299
10   0.100     0.001  7.708309
9    0.010     1.000  7.708334
11   0.100     0.250  7.708653
15   0.500     0.001  7.708786
12   0.100     0.500  7.708998
20   1.000     0.001  7.709320
13   0.100     0.750  7.709344
14   0.100     1.000  7.709691
25   1.500     0.001  7.709793
30   2.000     0.001  7.710213
35   2.000     0.001  7.710213
16   0.500     0.250  7.710490
17   0.500     0.500  7.712215
21   1.000     0.250  7.712696
45   5.000     0.001  7.712706
40   5.000     0.001  7.712706
18   0.500     0.750  7.713959
26   1.500     0.250  7.714810
19   0.500     1.000  7.715714
50  10.000     0.001  7.716001
22   1.000     0.500  7.716144
36   2.000     0.250  7.716855
31   2.000     0.250  7.716855
23   1.000     0.750  7.719652
27   1.500     0.500  7.719976
24   1.000     1.000  7.723271
32   2.000     0.500  7.724066
37   2.000     0.500  7.724066
28   1.500     0.750  7.725594
41   5.000     0.250  7.729555
46   5.000     0.250  7.729555
29   1.500     1.000  7.731425
38   2.000     0.750  7.731788
33   2.000     0.750  7.731788
34   2.000     1.000  7.740793
39   2.000     1.000  7.740793
42   5.000     0.500  7.752584
47   5.000     0.500  7.752584
51  10.000     0.250  7.752897
43   5.000     0.750  7.768792
48   5.000     0.750  7.768792
44   5.000     1.000  7.778317
49   5.000     1.000  7.778317
52  10.000     0.500  7.780756
53  10.000     0.750  7.788450
54  10.000     1.000  7.798394