In [1]:
from sentence_transformers import SentenceTransformer
from tqdm import tqdm
import pandas as pd
import numpy as np
import torch
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer, AutoModel

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2',
                                          token="<token_here>")

model = AutoModel.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')

c:\Python\anaconda3\envs\hf\Lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [3]:
type(model)

transformers.models.bert.modeling_bert.BertModel

In [4]:
inputs = tokenizer(["Hello world!"], return_tensors="pt")
input_ids = inputs["input_ids"]
input_ids

tensor([[ 101, 7592, 2088,  999,  102]])

In [5]:
tokens = tokenizer.convert_ids_to_tokens(input_ids[0])
print(tokens)

['[CLS]', 'hello', 'world', '!', '[SEP]']


In [6]:
with torch.no_grad():
    outputs = model(**inputs)
emb = outputs.last_hidden_state.mean(dim=1)
print(outputs.last_hidden_state.shape)
print(emb.shape)  

torch.Size([1, 5, 384])
torch.Size([1, 384])


In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2',
                            token="<token_here>")
embeddings = model.encode(["Hello world!"])
print(embeddings.shape) 
type(model) 

(1, 384)


sentence_transformers.SentenceTransformer.SentenceTransformer

In [8]:
embeddings

array([[-2.03868169e-02,  2.52807923e-02, -5.66245290e-04,
         1.16154198e-02, -3.79884504e-02, -1.19981192e-01,
         4.17094193e-02, -2.08571218e-02, -5.90067618e-02,
         2.42325701e-02,  6.21202290e-02,  6.76799268e-02,
         3.31002288e-02, -1.03693837e-02, -3.12157311e-02,
        -3.27332169e-02, -2.11176509e-03,  9.26196296e-03,
        -1.24764554e-01,  1.12368157e-02,  3.90454493e-02,
         5.44024855e-02, -2.82553141e-03,  4.45562825e-02,
        -8.54202211e-02, -2.28736997e-02,  3.91405523e-02,
         3.60468514e-02, -3.21268067e-02, -6.42586946e-02,
         5.81290796e-02,  4.66908813e-02,  8.06156173e-02,
        -7.73425912e-03, -2.20832005e-02,  6.71314746e-02,
        -4.50414456e-02, -1.02121234e-01,  1.26439147e-03,
         4.68019769e-02,  2.63959114e-02, -6.99095726e-02,
        -4.45334725e-02, -6.90196082e-03,  1.92886163e-02,
         2.05908585e-02,  6.51809387e-03,  3.54938544e-02,
         1.03933103e-01,  1.75037272e-02, -4.29428332e-0

In [12]:
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium."
]
embeddings = model.encode(sentences)

In [10]:
similarities = model.similarity(embeddings, embeddings)
print(similarities.shape)


torch.Size([3, 3])


In [11]:
similarities

tensor([[1.0000, 0.6660, 0.1046],
        [0.6660, 1.0000, 0.1411],
        [0.1046, 0.1411, 1.0000]])

One can also try model `BAAI/bge-small-en-v1.5`