In [1]:
# # pip uninstall tensorflow
# # pip install tensorflow-cpu
# !pip install keras

In [2]:
import numpy as np
import tensorflow
import keras
from keras.utils import to_categorical

In [3]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [4]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [5]:
int_to_char = dict(list(enumerate(alphabets)))

In [6]:
int_to_char[6]

'G'

In [7]:
dict((v,i) for i,v in enumerate(alphabets))

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [8]:
char_to_int = dict((v,i) for i,v in enumerate(alphabets))

In [9]:
char_to_int['X']

23

Prepare the dataset

In [35]:
x = []
y = []
seq_length = 1

for i in range(len(alphabets)-seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1]
    print(seq_in, '-->',seq_out)
    x+=[[char_to_int[seq_in[0]]]]
    y += [char_to_int[seq_out]]

['A'] --> B
['B'] --> C
['C'] --> D
['D'] --> E
['E'] --> F
['F'] --> G
['G'] --> H
['H'] --> I
['I'] --> J
['J'] --> K
['K'] --> L
['L'] --> M
['M'] --> N
['N'] --> O
['O'] --> P
['P'] --> Q
['Q'] --> R
['R'] --> S
['S'] --> T
['T'] --> U
['U'] --> V
['V'] --> W
['W'] --> X
['X'] --> Y
['Y'] --> Z


In [36]:
len(x)

25

In [12]:
x = np.reshape(x,(25,1,1))
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [13]:
x_norm = x/25

In [14]:
x_norm

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [16]:
y_new = to_categorical(y)

In [17]:
y_new.shape

(25, 26)

In [19]:
x_norm.shape

(25, 1, 1)

Build the model

In [20]:
from keras.layers import SimpleRNN,Dense,Input
from keras.models import Sequential

In [23]:
model = Sequential()
model.add(Input((1,1)))
model.add(Dense(25,activation = 'relu'))
model.add(SimpleRNN(32))
model.add(Dense(26,activation = 'softmax'))

In [24]:
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

Train the model

In [25]:
model.fit(x_norm,y_new,epochs = 500,batch_size = 1)

Epoch 1/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.0000e+00 - loss: 3.2886
Epoch 2/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2613   
Epoch 3/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2504   
Epoch 4/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0400 - loss: 3.2393    
Epoch 5/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2285    
Epoch 6/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2174   
Epoch 7/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.2087    
Epoch 8/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.1963   
Epoch 9/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0400 - loss: 3.1852   
Epoch 10/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0800 - loss: 3.1733   
Epoch 11/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0800 - loss: 3.1610   
Epoch 12/500
25/25 ━━━━━━━

In [31]:
model.evaluate(x_norm,y_new,batch_size = 1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9600 - loss: 1.1021    


[1.1020921468734741, 0.9599999785423279]

In [34]:
new = 'M'
new = char_to_int[new]
new = np.reshape(new,(1,1,1,1))
new = new/25
pred = model.predict(new,verbose = False)
pred = np.argmax(pred)
int_to_char[pred]

'N'

`For seq_length = 3`

In [37]:
x = []
y = []
seq_length = 3

for i in range(len(alphabets)-seq_length):
    seq_in = alphabets[i:i + seq_length]
    seq_out = alphabets[i+seq_length]
    print(seq_in, '-->',seq_out)
    x.append([char_to_int[char] for char in seq_in])
    y += [char_to_int[seq_out]]

ABC --> D
BCD --> E
CDE --> F
DEF --> G
EFG --> H
FGH --> I
GHI --> J
HIJ --> K
IJK --> L
JKL --> M
KLM --> N
LMN --> O
MNO --> P
NOP --> Q
OPQ --> R
PQR --> S
QRS --> T
RST --> U
STU --> V
TUV --> W
UVW --> X
VWX --> Y
WXY --> Z


In [38]:
len(x)

23

In [39]:
x = np.reshape(x,(23,seq_length,1))
x

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

In [41]:
x_norm = x/25

In [42]:
x_norm

array([[[0.  ],
        [0.04],
        [0.08]],

       [[0.04],
        [0.08],
        [0.12]],

       [[0.08],
        [0.12],
        [0.16]],

       [[0.12],
        [0.16],
        [0.2 ]],

       [[0.16],
        [0.2 ],
        [0.24]],

       [[0.2 ],
        [0.24],
        [0.28]],

       [[0.24],
        [0.28],
        [0.32]],

       [[0.28],
        [0.32],
        [0.36]],

       [[0.32],
        [0.36],
        [0.4 ]],

       [[0.36],
        [0.4 ],
        [0.44]],

       [[0.4 ],
        [0.44],
        [0.48]],

       [[0.44],
        [0.48],
        [0.52]],

       [[0.48],
        [0.52],
        [0.56]],

       [[0.52],
        [0.56],
        [0.6 ]],

       [[0.56],
        [0.6 ],
        [0.64]],

       [[0.6 ],
        [0.64],
        [0.68]],

       [[0.64],
        [0.68],
        [0.72]],

       [[0.68],
        [0.72],
        [0.76]],

       [[0.72],
        [0.76],
        [0.8 ]],

       [[0.76],
        [0.8 ],
        [0.84]],



In [43]:
y_new = to_categorical(y)

In [44]:
y_new.shape

(23, 26)

In [45]:
x_norm.shape

(23, 3, 1)

In [49]:
model = Sequential()
model.add(Input((seq_length,1)))
model.add(Dense(25,activation = 'relu'))
model.add(SimpleRNN(32))
model.add(Dense(26,activation = 'softmax'))

In [50]:
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [51]:
model.fit(x_norm,y_new,epochs = 1000,batch_size = 1)

Epoch 1/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0000e+00 - loss: 3.3161
Epoch 2/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0435 - loss: 3.2588   
Epoch 3/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0435 - loss: 3.2349   
Epoch 4/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.2083   
Epoch 5/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.1860    
Epoch 6/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.1550
Epoch 7/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.1265   
Epoch 8/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0435 - loss: 3.1034   
Epoch 9/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 3.0645   
Epoch 10/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0870 - loss: 3.0349   
Epoch 11/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0435 - loss: 2.9950   
Epoch 12/1000
23

In [57]:
new = 'WXY'
val = np.array([[char_to_int[x]] for x in new])
val = val.reshape(1,3,1)
val = val/25
result = model.predict(val,verbose = False)
result = np.argmax(result)
print(new,'-->',int_to_char[result])

WXY --> Z
