In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [20]:
glass = pd.read_csv("C:/Python/Cases/Glass_Identification/Glass.csv")
X = glass.drop('Type', axis=1)
le = LabelEncoder()
y = le.fit_transform( glass['Type'] )
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [19]:
le.classes_

array(['building_windows_float_processed',
       'building_windows_non_float_processed', 'containers', 'headlamps',
       'tableware', 'vehicle_windows_float_processed'], dtype=object)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,
                                                    stratify=y)

In [28]:
solver = 'saga'
penalties = ['l2','l1','elasticnet',None]
scores = []
for p in penalties:
    lr = LogisticRegression(solver=solver, penalty=p, l1_ratio=0.5)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    scores.append([p, accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame( scores, columns=['penalty','score'] )
df_scores.sort_values('score', ascending=False)

c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\

penalty     score
0          l2  0.538462
1          l1  0.538462
2  elasticnet  0.538462
3        None  0.538462

In [29]:
solver = ['sag','newton-cg','newton-cholesky','lbfgs']
penalties = ['l2',None]
scores = []
for p in penalties:
    for s in solver:
        lr = LogisticRegression(solver=s, penalty=p)
        lr.fit(X_train, y_train)
        y_pred = lr.predict(X_test)
        scores.append([p,s, accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame( scores, columns=['penalty','solver','score'] )
df_scores.sort_values('score', ascending=False)

c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Python\anaconda3\envs\hf\Lib\site-packages\s

penalty           solver     score
1      l2        newton-cg  0.661538
2      l2  newton-cholesky  0.661538
3      l2            lbfgs  0.661538
5    None        newton-cg  0.630769
6    None  newton-cholesky  0.630769
7    None            lbfgs  0.615385
0      l2              sag  0.553846
4    None              sag  0.538462

In [33]:
lr = LogisticRegression(solver='newton-cg', penalty='l2')
lr.fit(X_train, y_train)
y_pred_prob = lr.predict_proba(X_test)
y_pred = lr.predict(X_test)

In [ ]:
y_pred_prob.argmax(axis=1)from fimim

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 3, 0, 1, 4, 3, 0, 3, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 2, 0, 1, 2, 3, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       3, 1, 1, 1, 1, 3, 1, 1, 0, 0, 1, 1, 3, 3, 0, 0, 3, 1, 1, 0, 1],
      dtype=int64)

In [34]:
y_pred

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 3, 0, 1, 4, 3, 0, 3, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 2, 0, 1, 2, 3, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       3, 1, 1, 1, 1, 3, 1, 1, 0, 0, 1, 1, 3, 3, 0, 0, 3, 1, 1, 0, 1])

In [35]:
accuracy_score( y_test, y_pred )

0.6615384615384615

In [39]:
le.classes_

array(['building_windows_float_processed',
       'building_windows_non_float_processed', 'containers', 'headlamps',
       'tableware', 'vehicle_windows_float_processed'], dtype=object)

In [38]:
print( classification_report( y_test, y_pred ) )

              precision    recall  f1-score   support

           0       0.65      0.71      0.68        21
           1       0.61      0.74      0.67        23
           2       0.50      0.50      0.50         4
           3       0.89      0.89      0.89         9
           4       1.00      0.33      0.50         3
           5       0.00      0.00      0.00         5

    accuracy                           0.66        65
   macro avg       0.61      0.53      0.54        65
weighted avg       0.63      0.66      0.63        65



c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Python\anaconda3\envs\hf\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [9]:
X_test.shape

(65, 9)