In [1]:
import numpy as np

In [10]:
#from list
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3,],[4,5,6]])
arr3 = np.array((7,8,9))
print(arr1,"\n",arr2,"\n",arr3)

[1 2 3 4] 
 [[1 2 3]
 [4 5 6]] 
 [7 8 9]


In [5]:
#from functions
zeros = np.zeros((2,3))
ones = np.ones((3,2))
identity =np.eye(3)
zeros,ones,identity

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [11]:
#uninitialized
empty = np.empty((2,2))
full = np.full((2,2),7)
empty,full


(array([[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323]]),
 array([[7, 7],
        [7, 7]]))

In [13]:
#arange:steps, last one is not included for computation
#linspace: number of points, last one is included
arange_ex = np.arange(0,10,2)
linspace_ex = np.linspace(0,1,5)
arange_ex,linspace_ex

(array([0, 2, 4, 6, 8]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
#Random arrays
rand = np.random.rand(2,3) #between 0 and 1
np.random.uniform(1,100,10) # 1 to 100,reasonably uniformed
np.random.randint(1,10,(2,2)) #1 to 10
np.random.randn(2,3)  #normal dist
np.random.normal(5,2,(2,3)) #mean =5,std =2
