In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

In [19]:
insure = pd.read_csv("C:/Python/Datasets/Insure_auto.csv")
X = insure[['Home']]
y = insure['Operating_Cost']

In [20]:
lr = LinearRegression()

Polynomial with Degree = 2

In [21]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

Home    Home^2
0  400.0  160000.0
1  350.0  122500.0
2  600.0  360000.0
3  800.0  640000.0
4  900.0  810000.0
5  200.0   40000.0
6  120.0   14400.0
7  340.0  115600.0
8  490.0  240100.0
9  700.0  490000.0

In [22]:
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_

(array([57.28485112,  0.15387525]), 54381.71562081709)

y = 54381.71562081709 + 57.28*x +  0.15387525*(x^2)

Polynomial with Degree = 3

In [29]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

Home  Automobile    Home^2  Home Automobile  Automobile^2       Home^3  \
0  400.0      1200.0  160000.0         480000.0     1440000.0   64000000.0   
1  350.0       360.0  122500.0         126000.0      129600.0   42875000.0   
2  600.0       800.0  360000.0         480000.0      640000.0  216000000.0   
3  800.0      1800.0  640000.0        1440000.0     3240000.0  512000000.0   
4  900.0      1600.0  810000.0        1440000.0     2560000.0  729000000.0   
5  200.0      1000.0   40000.0         200000.0     1000000.0    8000000.0   
6  120.0       900.0   14400.0         108000.0      810000.0    1728000.0   
7  340.0      1100.0  115600.0         374000.0     1210000.0   39304000.0   
8  490.0       900.0  240100.0         441000.0      810000.0  117649000.0   
9  700.0       800.0  490000.0         560000.0      640000.0  343000000.0   

   Home^2 Automobile  Home Automobile^2  Automobile^3  
0       1.920000e+08       5.760000e+08  1.728000e+09  
1       4.410000e+07       4.536000e+07  4.665600e+07  
2       2.880000e+08       3.840000e+08  5.120000e+08  
3       1.152000e+09       2.592000e+09  5.832000e+09  
4       1.296000e+09       2.304000e+09  4.096000e+09  
5       4.000000e+07       2.000000e+08  1.000000e+09  
6       1.296000e+07       9.720000e+07  7.290000e+08  
7       1.271600e+08       4.114000e+08  1.331000e+09  
8       2.160900e+08       3.969000e+08  7.290000e+08  
9       3.920000e+08       4.480000e+08  5.120000e+08

In [24]:
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_

(array([ 3.44882529e+02, -5.18115986e-01,  4.46482717e-04]), 21978.25877601611)

y = 21978.25877601611 + 3.44882529e+02*x - 5.18115986e-01(x^2) + 4.46482717e-04(x^3)

Both the variables

In [25]:
X = insure[['Home','Automobile']]
y = insure['Operating_Cost']

In [26]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

Home  Automobile    Home^2  Home Automobile  Automobile^2
0  400.0      1200.0  160000.0         480000.0     1440000.0
1  350.0       360.0  122500.0         126000.0      129600.0
2  600.0       800.0  360000.0         480000.0      640000.0
3  800.0      1800.0  640000.0        1440000.0     3240000.0
4  900.0      1600.0  810000.0        1440000.0     2560000.0
5  200.0      1000.0   40000.0         200000.0     1000000.0
6  120.0       900.0   14400.0         108000.0      810000.0
7  340.0      1100.0  115600.0         374000.0     1210000.0
8  490.0       900.0  240100.0         441000.0      810000.0
9  700.0       800.0  490000.0         560000.0      640000.0

In [27]:
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_

(array([ 1.47533405e+02,  5.88905218e+01, -7.94261684e-02,  9.36654775e-02,
        -2.65057986e-02]),
 -1455.231030816125)