In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

In [2]:
job = pd.read_csv("C:/Python/Datasets/JobSalary2.csv", index_col=0)
job.isnull().sum()

Computer     2
Marketing    1
Engineer     0
dtype: int64

In [3]:
imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')
imputer.fit(job) # calculates mean of every column
imputer.statistics_

array([75.33333333, 52.57142857, 85.625     ])

In [4]:
imputer.transform(job)

Computer  Marketing  Engineer
S_No                                
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0

In [5]:
imputer = SimpleImputer(strategy='median').set_output(transform='pandas')
imputer.fit(job) # calculates median of every column
imputer.statistics_

array([76. , 53. , 86.5])

In [6]:
imputer.transform(job)

Computer  Marketing  Engineer
S_No                               
1         84.0       55.0      75.0
2         90.0       53.0      70.0
3         63.0       53.0      88.0
4         76.0       50.0      77.0
5         63.0       41.0      89.0
6         75.0       54.0      85.0
7         76.0       51.0      96.0
8         77.0       64.0     105.0

In [7]:
imputer.fit_transform(job)

Computer  Marketing  Engineer
S_No                               
1         84.0       55.0      75.0
2         90.0       53.0      70.0
3         63.0       53.0      88.0
4         76.0       50.0      77.0
5         63.0       41.0      89.0
6         75.0       54.0      85.0
7         76.0       51.0      96.0
8         77.0       64.0     105.0

In [8]:
concrete = pd.read_csv("C:/Python/Cases/Concrete_Strength/Concrete_Data.csv")
X = concrete.drop('Strength', axis=1)
y = concrete['Strength']

In [9]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [10]:
tst = pd.read_csv("C:/Python/Cases/Concrete_Strength/testConcreteMissing.csv")
tst

Cement  Blast   Fly  Water  Superplasticizer  Coarse   Fine    Age
0    495.0  120.0   0.0  155.0               5.0   866.0  884.0   75.0
1    262.0  129.0   0.0    NaN               2.0   808.0    NaN  174.0
2      NaN   48.0   1.0  215.0               5.0   807.0  839.0  113.0
3    329.0  141.0   0.0  286.0               NaN   881.0  823.0    NaN
4    354.0   14.0   0.0  129.0               2.0   839.0    NaN  210.0
5    150.0   23.0   NaN  114.0               4.0   883.0  638.0   36.0
6    480.0   64.0   0.0  292.0               3.0   896.0    NaN  180.0
7    393.0   49.0  82.0  132.0               1.0     NaN  830.0  271.0
8    284.0   63.0   1.0    NaN               1.0   804.0  725.0   44.0
9    206.0   38.0   0.0  103.0               NaN   818.0  719.0  191.0
10   247.0   64.0  26.0  175.0               2.0   822.0  898.0  183.0
11     NaN  102.0   0.0  110.0               2.0   808.0    NaN  270.0
12   457.0    NaN   0.0  289.0               3.0   829.0  865.0  190.0
13   125.0   93.0   0.0  200.0               5.0   893.0  671.0  113.0

In [11]:
imputer = SimpleImputer().set_output(transform='pandas')
imputer.fit(X)
tst_imp = imputer.transform(tst)
lr.predict( tst_imp )

array([68.73718457, 44.92754382, 29.09844489, 27.43221577, 56.55844543,
       18.83513067, 50.30685651, 81.86351485, 24.60173472, 42.79473839,
       43.44332935, 66.11413244, 50.80518635, 15.38709673])

#### Chemical Process

In [12]:
chem = pd.read_csv("C:/Python/Cases/Chemical_Process_Data/ChemicalProcess.csv")
y = chem['Yield']
X = chem.drop('Yield', axis=1)

In [13]:
y.isnull().sum()

0

In [14]:
X.isnull().sum().sum()

106

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [16]:
X_train.isnull().sum().sum()

80

In [17]:
X_test.isnull().sum().sum()

26

In [18]:
imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')
imputer.fit(X_train)
X_trn_imp = imputer.transform(X_train)
X_trn_imp.isnull().sum().sum()

0

In [19]:
X_tst_imp = imputer.transform(X_test)
X_tst_imp.isnull().sum().sum()

0

In [20]:
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

5.465628884535992

Median Imputation

In [22]:
imputer = SimpleImputer(strategy='median').set_output(transform='pandas')
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

5.216438609180479

#### Iterative Imputer

In [23]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [28]:
imputer = IterativeImputer(initial_strategy='mean')
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

6.451138259426837

In [29]:
imputer = IterativeImputer(initial_strategy='median')
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
lr = LinearRegression()
lr.fit(X_trn_imp, y_train)
y_pred = lr.predict(X_tst_imp)
mean_absolute_error(y_test, y_pred)

6.448873070423986

In [31]:
airquality = pd.read_csv("C:/Python/Datasets/Airquality.csv")
airquality.isnull().sum()

Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64

In [38]:
imputer = IterativeImputer(initial_strategy='mean').set_output(transform='pandas')
imp_air = imputer.fit_transform(airquality)
imp_air.isnull().sum()

Ozone      0
Solar.R    0
Wind       0
Temp       0
Month      0
Day        0
dtype: int64

In [39]:
imp_air

Ozone     Solar.R  Wind  Temp  Month   Day
0    41.000000  190.000000   7.4  67.0    5.0   1.0
1    36.000000  118.000000   8.0  72.0    5.0   2.0
2    12.000000  149.000000  12.6  74.0    5.0   3.0
3    18.000000  313.000000  11.5  62.0    5.0   4.0
4   -12.272303  141.910042  14.3  56.0    5.0   5.0
..         ...         ...   ...   ...    ...   ...
148  30.000000  193.000000   6.9  70.0    9.0  26.0
149  29.203097  145.000000  13.2  77.0    9.0  27.0
150  14.000000  191.000000  14.3  75.0    9.0  28.0
151  18.000000  131.000000   8.0  76.0    9.0  29.0
152  20.000000  223.000000  11.5  68.0    9.0  30.0

[153 rows x 6 columns]