In [30]:
import numpy as np
from pprint import pprint

from numpy.ma.core import shape

In [31]:
l=[10,20,30,40]
n=np.array(l,dtype="int64")
print(n)

[10 20 30 40]


## Basic methods


In [33]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
pprint(a)
pprint(b)
print('\n')
print("Add:",a+b)
print("Sub:",a-b)
print("Mult:",a*b)
print("Divide",a/b)
# print(a@b)

array([[5, 7, 6],
       [1, 5, 5],
       [8, 5, 9]], dtype=int32)
array([[4, 6, 1],
       [4, 4, 5],
       [2, 5, 4]], dtype=int32)


Add: [[ 9 13  7]
 [ 5  9 10]
 [10 10 13]]
Sub: [[ 1  1  5]
 [-3  1  0]
 [ 6  0  5]]
Mult: [[20 42  6]
 [ 4 20 25]
 [16 25 36]]
Divide [[1.25       1.16666667 6.        ]
 [0.25       1.25       1.        ]
 [4.         1.         2.25      ]]


## reshape, resize
(new array(id change), data remains same),(original array(id change) update,can add or delete data)

(No padding),(padding)

In [75]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(id(a))
print(id(a.reshape((3,3))))
print(a)

a=np.array([1,2,3,4,5,6,7,8,9])
print(id(a))
print(id(a.resize((2,2))))
print(a)

2166440469264
2166440707056
[1 2 3 4 5 6 7 8 9]
2166440707056
140732722573808
[[1 2]
 [3 4]]


## Concatenate

In [61]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[1,4,3],[6,3,4]])

pprint(np.concatenate((a,b),axis=0))

pprint(np.concatenate((a,b),axis=1))

array([[1, 2, 3],
       [2, 3, 4],
       [1, 4, 3],
       [6, 3, 4]])
array([[1, 2, 3, 1, 4, 3],
       [2, 3, 4, 6, 3, 4]])


In [77]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [84]:
x=np.random.choice([1,2,3,54,6,78])
print(x)

1
