In [4]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
#Broadcasting
arr[0:5] =100

In [7]:
#imp note
slice_of_arr = arr[0:6]
slice_of_arr[:] =99
print(arr)

arr = np.arange(0,11)
slice_of_arr = arr.copy()
slice_of_arr[:] = 89
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
#conditionals
bool_arr = arr>4
arr[bool_arr]
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
#creating a sample array
arr.sum()
arr.max()
arr.min()
arr.mean(),arr.var(),arr.std()

(np.float64(5.0), np.float64(10.0), np.float64(3.1622776601683795))