## Numpy
linespace arange

In [2]:
import numpy as np

In [5]:
np.arange(0,10,2).tolist()

[0, 2, 4, 6, 8]

In [7]:
np.linspace(0,10,20) ## including the start and last

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))*20

array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]])

#### random /

In [13]:
np.random.randint(0,100,5)

array([16, 68, 34, 96, 46], dtype=int32)

In [21]:
np.random.choice(10,5)
#np.random.choice([1,2,34,5],2)

array([4, 5, 5, 5, 9], dtype=int32)

## Distributions

In [24]:
np.random.randn(4,2) ## mean=0,std =1

array([[ 0.64842495, -0.84576649],
       [-1.02854504, -1.93533923],
       [-0.58685027, -0.96463186],
       [-1.43254236,  0.47399132]])

In [25]:
np.random.normal(1,5,12) ## means =1 and std =5

array([ 1.51753917e+00,  8.95302105e+00,  7.10849345e+00, -1.67389033e+00,
        2.16258299e+00,  6.76887046e+00,  4.39787384e+00,  6.69135942e+00,
       -1.03002452e+01,  9.81675594e-01,  5.82655955e-03,  5.07477573e+00])

In [26]:
np.random.uniform(0,10,5)

array([4.43481044, 9.14986625, 0.71029674, 1.76674725, 5.91580964])

## Basic ops filter aggregate

In [50]:
arr=np.arange(1,11)

In [51]:
print(f"min:{arr.min()},max:{arr.max()},var:{arr.var()},Std:{arr.std()},sum:{arr.sum()}")


min:1,max:10,var:8.25,Std:2.8722813232690143,sum:55


In [52]:
arr[(arr>2 )& (arr<6)]

array([3, 4, 5])

In [53]:
list=arr[:5]
list

array([1, 2, 3, 4, 5])

## ***very imp concept***

In [60]:
arr=np.arange(1,11)
print(id(arr))
list=arr[:5]
print(list)
print(id(list))
list[:]=100 ## only possible in np array
print(list)
print(id(list))
print(arr)
print(id(arr))

1882088465744
[1 2 3 4 5]
1882088456336
[100 100 100 100 100]
1882088456336
[100 100 100 100 100   6   7   8   9  10]
1882088465744


In [75]:
arr=np.arange(1,11)
l=arr[:5].copy()
l[:]=55
print(l)
print(arr)

[55 55 55 55 55]
[ 1  2  3  4  5  6  7  8  9 10]


##### In list it create a new array

In [74]:
arr=np.arange(1,11)
l=arr[:5].tolist()
l[:]=[12]*len(l)
print(arr)
print(l)

[ 1  2  3  4  5  6  7  8  9 10]
[12, 12, 12, 12, 12]


### There is a Catch

In [81]:
arr=[[1],[2],[3],[4],[5]]
l=arr[:3]
l[0][0]=55
print(arr)
print(l)

print('Deep Copy')
# Use the deep copy (because the list containing the mutable obj)
import copy
arr=[[1],[2],[3],[4],[5]]
l=copy.deepcopy(arr[:3])
l[0][0]=55
print(arr)
print(l)


[[55], [2], [3], [4], [5]]
[[55], [2], [3]]
Deep Copy
[[1], [2], [3], [4], [5]]
[[55], [2], [3]]
