In [27]:
import numpy as np
import pandas as pd
import kagglehub

# Download latest version
# path = kagglehub.dataset_download("nxtwaveda/data-analyst")
#
# print("Path to dataset files:", path)

Path to dataset files: C:\Users\dai\.cache\kagglehub\datasets\nxtwaveda\data-analyst\versions\2


## numpy

In [21]:
emps = np.array([[1,'abc',99000],[2,'mno',28000]])

In [7]:
name = input()
for emp in emps:
    if emp[1].lower().strip() == name:
        print(emp[1],": ",emp[0],emp[2])



abc :  1 99000


In [64]:
my_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40}
print(np.array(list(my_dict.values())))

[10 20 30 40]


In [70]:
data_dict = {
    'temperatures': [25, 30, 28, 32],
    'humidity': [60, 65, 70, 55],
    'pressure': [1013, 1015, 1010, 1012]
}
print(np.array(list(data_dict.values())))

[[  25   30   28   32]
 [  60   65   70   55]
 [1013 1015 1010 1012]]


In [81]:
person_dict = {
    'names': ['Alice', 'Bob', 'Charlie'],
    'ages': [25, 30, 35],
    'scores': [85.5, 92.0, 78.5]
}
print(np.array(list(person_dict.values())))
print()
dtype = [('names','U10'),('ages','i4'),('scores','f4')]
np.array(list(zip(person_dict['names'],person_dict['ages'],person_dict['scores'])))

[['Alice' 'Bob' 'Charlie']
 ['25' '30' '35']
 ['85.5' '92.0' '78.5']]



array([['Alice', '25', '85.5'],
       ['Bob', '30', '92.0'],
       ['Charlie', '35', '78.5']], dtype='<U32')

## Pandas

In [30]:
l =[10,20,30,40,"50"]
print(pd.Series(l,index=['a','b','c','d','e']))

a    10
b    20
c    30
d    40
e    50
dtype: object


In [22]:
x={"empid":[1,2],"ename":["abc","mno"],"salary":[88,34]}
y=[{"eid":1,"name":"Pankaj","salary":88},{"eid":2,"name":"Suraj","salary":34}]

In [24]:
tb=pd.DataFrame(x)
print(tb)
print()
print(tb.describe())
print()

tb2=pd.DataFrame(y)
print(tb2)
print(tb2.describe())

   empid ename  salary
0      1   abc      88
1      2   mno      34

          empid     salary
count  2.000000   2.000000
mean   1.500000  61.000000
std    0.707107  38.183766
min    1.000000  34.000000
25%    1.250000  47.500000
50%    1.500000  61.000000
75%    1.750000  74.500000
max    2.000000  88.000000

   eid    name  salary
0    1  Pankaj      88
1    2   Suraj      34
            eid     salary
count  2.000000   2.000000
mean   1.500000  61.000000
std    0.707107  38.183766
min    1.000000  34.000000
25%    1.250000  47.500000
50%    1.500000  61.000000
75%    1.750000  74.500000
max    2.000000  88.000000


In [47]:
emp_list = list()
class Employee:
    _eid =1
    def __init__(self,ename,basic_sal):
        Employee._eid+=1
        self._ename = ename
        self._basic_sal = basic_sal
        self._pfp = 12
        self._pt = 200
        self._hrap = 50
        self._ma = 1000

    def calc_gross(self):
        pf = self._pfp*self._basic_sal/100
        hra = self._hrap*self._basic_sal/100
        return self._basic_sal+hra+self._ma

    def calc_net(self):
        pf = self._pfp*self._basic_sal/100
        return self.calc_gross()-pf-self._pt

    def __str__(self):
        return f"{self._eid} {self._ename} {self._basic_sal} {self._pfp} {self._pt} {self._hrap} {self._ma} {self.calc_net()} {self.calc_net()}"


class Manager(Employee):
    def __init__(self,ename,basic_sal):
        super().__init__(ename,basic_sal)
        self.man_allow_per = 8
        self.food_allow_per = 10
        self.other_allow_per = 3

    def calc_gross(self):
        return super().calc_gross()+self.man_allow_per*self._basic_sal/100+self.food_allow_per*self._basic_sal/100+self.other_allow_per*self._basic_sal/100

    def calc_net(self):
        pf = self._pfp*self._basic_sal/100
        return self.calc_gross()-pf-self._pt

    # def __str__(self):
    #     return f"{self._eid} {self._ename} {self._basic_sal} {self._pfp} {self._pt} {self._hrap} {self._ma} {self.man_allow_per} {self.food_allow_per} {self.other_allow_per}"

class MarkExecutive(Employee):
    def __init__(self,ename,basic_sal,kms_travelled):
        super().__init__(ename,basic_sal)
        self.kms_travelled = kms_travelled
        self.phone_allow = 1000
        self.travel_allow = 5*kms_travelled

    def calc_gross(self):
        return super().calc_gross()+self.phone_allow+self.travel_allow

    def calc_net(self):
        pf = self._pfp*self._basic_sal/100
        return self.calc_gross()-pf-self._pt

    # def __str__(self):
    #     return f"{self._eid} {self._ename} {self._basic_sal} {self._pfp} {self._pt} {self._hrap} {self._ma} {self.kms_travelled} {self.phone_allow} {self.travel_allow}"

In [50]:
e = Employee("Pankaj",50000)
m = Manager("Suraj",60000)

e2 = Employee("Ravi",70000)
m2 = Manager("Raj",80000)
emp_list = {"employees":[e,e2],"managers":[m,m2]}
print(pd.DataFrame(emp_list).columns)


Index(['employees', 'managers'], dtype='object')


In [60]:
dat = pd.read_csv('C:\\Users\\dai\\Downloads\\emp_sal.csv')
print(dat.head(2))
print()
print(dat.tail(1))

   eid     name  salary
0    1  Ganpati   30000
1    2   Ramesh   40000
   eid    name  salary
1    2  Ramesh   40000


In [7]:
d =pd.DataFrame({"empid":[1,2,3],"ename":["abc","mno","pqr"]},index=['one','two','three'])
# for i in d:                              #prints column names
#     print(i)

print(d['ename','salary']) #series
for i in d.loc('one'):   #for xlsx, you can only use loc(0)
    print(i)
print(d.iloc(0))  #when you have named indexes, pass indexes

one      abc
two      mno
three    pqr
Name: ename, dtype: object


ValueError: No axis named one for object type DataFrame

#read data from csv

In [10]:
data = pd.read_csv('C:\\Users\\dai\\Downloads\\emp_sal.csv')
data = pd.read_csv('C:\\Users\\dai\\Downloads\\emp_sal.csv')
print(data)

   eid     name  salary
0    1  Ganpati   30000
1    2   Ramesh   40000
2    3      abc   35456
3    4      tyu   67890
4    5      ggd   98980
5    6     jkjk   75646
6    7      NaN   64788


#read data from xlsx

In [19]:
emp = pd.read_excel('C:\\Users\\dai\\Downloads\\emp_sal_xl.xls',sheet_name="emp")
print(emp)
print()
print(emp['salary'])
print()
for i in emp.info:
    print(i)
print()
print(emp.describe())

   eid     name  salary
0    1  Ganpati   30000
1    2   Ramesh   40000
2    3      abc   35456
3    4      tyu   67890
4    5      ggd   98980
5    6     jkjk   75646
6    7      NaN   64788
0    30000
1    40000
2    35456
3    67890
4    98980
5    75646
6    64788
Name: salary, dtype: int64
<bound method DataFrame.info of    eid     name  salary
0    1  Ganpati   30000
1    2   Ramesh   40000
2    3      abc   35456
3    4      tyu   67890
4    5      ggd   98980
5    6     jkjk   75646
6    7      NaN   64788>
            eid        salary
count  7.000000      7.000000
mean   4.000000  58965.714286
std    2.160247  24981.107753
min    1.000000  30000.000000
25%    2.500000  37728.000000
50%    4.000000  64788.000000
75%    5.500000  71768.000000
max    7.000000  98980.000000


In [38]:
emp_50k = emp[emp['salary']>50000]
emp_50k.to_csv('new.csv')
x = pd.read_csv('new.csv',index_col="name")  #can add delimeter also
print(x)

      Unnamed: 0  eid  salary
name                         
tyu            3    4   67890
ggd            4    5   98980
jkjk           5    6   75646
NaN            6    7   64788


## Data Analyst Dataset

In [29]:
dad = pd.read_csv('C:\\Users\\dai\\.cache\\kagglehub\\datasets\\nxtwaveda\\data-analyst\\versions\\2')

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\dai\\.cache\\kagglehub\\datasets\\nxtwaveda\\data-analyst\\versions\\2'

##  SQL connectivity

In [ ]:
#con.commit()
#con.close()

In [30]:
import pymysql as pms

In [34]:
con = pms.connect(host="localhost",user="root",password="Anurag@1",database = "empman",autocommit = True)

In [35]:
sql_data = pd.read_sql('select * from employee_employee',con)


C:\Users\dai\AppData\Local\Temp\ipykernel_10352\1482970939.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sql_data = pd.read_sql('select * from employee_employee',con)
