In [76]:
import numpy as np
from fontTools.misc.arrayTools import vectorLength
from numpy.ma.core import masked_print_option

In [77]:
arr = np.array([-1,0,1,2,3,4,5,6,7,8,9,20,34,67,float('nan'),float('inf'),float('-inf'),3+2j])

In [78]:
# Write a NumPy program to get the numpy version and show numpy build configuration.
print(np.__version__, np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: Ope

In [79]:
# Write a NumPy program to get help on the add function.
print(help(np.add))

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [80]:
# Write a NumPy program to test whether none of the elements of a given array is zero.
print("It contains zero element/s") if((arr==0).any())  else print("It doesn't contain any zero")

It contains zero element/s


In [81]:
# Write a NumPy program to test whether any of the elements of a given array is non-zero.
print("It has non-zero element/s") if((arr!=0).any())  else print("It doesn't contain non-zero elements")

It has non-zero element/s


In [82]:
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a
# Number).
print("Contains infinity or not a number") if(np.any(np.isinf(arr)) or np.any(np.isna(arr))) else print("Doesnt contain infinity or NaN")

Contains infinity or not a number


In [83]:
# Write a NumPy program to test element-wise for positive or negative infinity.
arr2 = [True if np.isinf(n) else False for n in arr]
arr2

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False]

In [84]:
# Write a NumPy program to test element-wise for NaN of a given array.
arr2 = [True if np.isnan(n) else False for n in arr]
arr2

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False]

In [85]:
# Write a NumPy program to test element-wise for complex number, real number of a given array.
arr2 = [True if np.iscomplex(n) else False for n in arr]
arr2

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [86]:
# Also test whether a given number is a scalar type or not.
arri2 = [1,2,3,'python',[1,2,3],[1,2]]
print(True if np.isscalar(arri2) else False)

False


In [87]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
# less_equal) of two given arrays.
arri3 = np.array([1,2,3,4,5,6])
arri4 = np.array([5,68,39,1,0,-1])
# print(np.equal(arri3,arri4))
# print(np.less(arri3,arri4))
[True if n >m else False for n,m in zip(arri3,arri4)],[True if n >= m else False for n,m in zip(arri3,arri4)],[True if n < m else False for n,m in zip(arri3,arri4)],[True if n <=m else False for n,m in zip(arri3,arri4)]

([False, False, False, True, True, True],
 [False, False, False, True, True, True],
 [True, True, True, False, False, False],
 [True, True, True, False, False, False])

In [88]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of
# the memory occupied by the array.
arri3 = np.array([1, 7, 13, 105])
arri3.nbytes

32

In [89]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
np.hstack([np.zeros(10),np.ones(10),np.full(10,5)])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [90]:
# Write a NumPy program to create an array of the integers from 30 to70.
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [91]:
# Write a NumPy program to create an array of all the even integers from 30 to 70.
#print(np.arange(30,71,2))
arro2 = np.arange(30,71)
arro2[arro2%2==0]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [92]:
# Write a NumPy program to create a 3x3 identity matrix.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
# Write a NumPy program to generate a random number between 0 and 1.
np.random.random()

0.571431055683022

In [94]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal
# distribution.
np.random.normal(loc=0, scale=1, size=15)

array([ 1.67266998, -1.90703291,  0.13149383,  1.7367861 , -1.08394717,
        0.07846667,  0.10167332,  0.70460357,  0.00659959,  0.05645829,
        0.36908677,  0.61833386,  2.19035516, -0.89414583, -1.27091333])

In [95]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
# except the first and last.
# np.linspace(15,55,39.5)
arro2 = np.arange(15,56)
arro2[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [96]:
# Write a NumPy program to create a 3X4 array using and iterate over it.
arro2 = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
# print([i for n in arro2 for i in n])
for n in np.nditer(arro2): print(n, end=' ')

1 2 3 4 2 3 4 5 3 4 5 6 

In [ ]:
# Write a NumPy program to create a vector of length 10 with values evenly distributed between 5
# and 50.
np.linspace(5,50,10)

In [109]:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
# numbers in the range from 9 to 15.
vector= np.arange(0,21)
vector = vector[(vector>=9) & (vector<=15)]*-1
vector

vector = np.arange(0,21)
np.where((vector>=9) & (vector<=15),-vector,vector)

#np.negative()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [ ]:
# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
# np.random.choice(['he','she','me','they'],size=2)
np.random.randint(0,11,size =5)

In [ ]:
# Write a NumPy program to multiply the values of two given vectors.
arri3 = np.array([1,2,3,4])
arri4 = np.array([4,3,2,1])
# np.multiply(arri3,arri4)
arri3 * arri4

In [120]:
# Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
np.random.choice(10,21,(3,4))
# Write a NumPy program to find the number of rows and columns of a given matrix.
# Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
# equal to 1, and inside 0.
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1,
# 2, 3, 4, 5.
# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the
# main diagonal.
# Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row
# of a given array.
# Write a NumPy program to compute the inner product of two given vectors.
# Write a NumPy program to add a vector to each row of a given matrix.
# Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the
# points using matplotlib.
# Write a NumPy program to convert numpy dtypes to native python types.
# Write a NumPy program to find the missing data in a given array.
# Write a NumPy program to sort a given array by row and column in ascending order.
# Write a NumPy program to extract all numbers from a given array which are less and greater than a
# specified number.
# Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
# given number.
# Write a NumPy program to create an array of equal shape and data type of a given array.
# Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.
# Write a NumPy program to multiply two given arrays of same size element-by-element.

array([0, 1, 5, 8, 2, 4, 8, 5, 3, 1, 8, 3, 9, 7, 4, 3, 1, 3, 6, 5, 4],
      dtype=int32)